# Generated by Django 2.2.6 on 2020-01-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='catagory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
